Repository LifeSG/react-design-system, pull requests merged in 2023-10, with the labels that each got.

#325 [MISC][WL] add key to filter checkbox toggle
  src/filter/addons/filter-item-checkbox.tsx
Labels: bug

#327 Initial expanded state of Filter Item
  src/filter/filter-item.tsx
  src/filter/filter.tsx
  src/filter/types.ts
  stories/filter/filter.stories.mdx
  stories/filter/props-table.tsx
  tests/filter/filter.spec.tsx
Labels: enhancement

#318 [BOOKINGSG-4650][WK] created new countdown timer
  src/countdown-timer/countdown-timer.style.tsx
  src/countdown-timer/countdown-timer.tsx
  src/countdown-timer/index.ts
  src/countdown-timer/types.ts
  src/countdown-timer/use-timer.tsx
  src/index.ts
  src/util/time-helper.ts
  stories/countdown-timer/countdown-timer.stories.mdx
  stories/countdown-timer/doc-elements.tsx
  stories/countdown-timer/props-table.tsx
Labels: enhancement

#326 [MOL-14046][HFAH] auto uppercase IC input field for eWills & HDB carparking
  src/masked-input/masked-input.tsx
  src/masked-input/types.ts
  stories/form/form-masked-input/form-masked-input.stories.mdx
  stories/form/form-masked-input/props-table.tsx
Labels: enhancement

#329 [WX] add collapsible feature in accordion
  src/accordion/accordion-item.style.tsx
  src/accordion/accordion-item.tsx
  src/accordion/types.ts
  stories/accordion/accordion.stories.mdx
  stories/accordion/props-table.tsx
  tests/accordion/accordion.spec.tsx
Labels: enhancement

#330 Update incorrect tooltip import in docs
  stories/tooltip/tooltip.stories.mdx
Labels: documentation

#331 Add ColDiv
  src/layout/col-div.style.tsx
  src/layout/col-div.tsx
  src/layout/index.ts
  src/layout/types.ts
  stories/layout/col-div-props-table.tsx
  stories/layout/col-div.stories.mdx
  stories/layout/doc-elements.tsx
Labels: enhancement

#332 [WX]add maxlines to Text
  src/text/helper.ts
  src/text/text.tsx
  src/text/types.ts
  stories/text/props-table.tsx
Labels: enhancement

#334 Add Divider component
  src/divider/divider.style.tsx
  src/divider/divider.tsx
  src/divider/index.ts
  src/divider/types.ts
  src/index.ts
  src/layout/types.ts
  stories/divider/divider.stories.mdx
  stories/divider/doc-elements.tsx
  stories/divider/props-table.tsx
Labels: enhancement

#338 Error display bookingSG resource scheme
  src/error-display/error-display-data.tsx
  src/error-display/error-display.tsx
  src/error-display/types.ts
  stories/error-display/error-display.stories.mdx
  stories/error-display/props-table.tsx
  tests/error-display/error-display.spec.tsx
Labels: enhancement

#335 Refactor day cell
  src/shared/internal-calendar/calendar-manager.style.tsx
  src/shared/internal-calendar/calendar-manager.tsx
  src/shared/internal-calendar/day-cell/day-cell.style.tsx
  src/shared/internal-calendar/day-cell/day-cell.tsx
  src/shared/internal-calendar/day-cell/index.ts
  src/shared/internal-calendar/day-cell/types.tsx
  src/shared/internal-calendar/internal-calendar.tsx
  src/shared/internal-calendar/internal-week-selection-calendar-day.tsx
  src/shared/internal-calendar/week/week-day-cell.tsx
  src/util/calendar-helper.ts
  tests/utils/calendar-helper.spec.ts
Labels: enhancement

#340 Specified N1 colour for text in alert boxes
  src/alert/alert.style.tsx
  tests/alert/alert.spec.tsx
Labels: bug

#341 Doc updates to use v2 stylesheet
  CONVENTIONS.md
  stories/getting-started/installation.stories.mdx
Labels: documentation
