Repository LifeSG/react-design-system, pull requests merged in 2023-12, with the labels that each got.

#371 [MISC][DS] bugfix for nested-select not updating dropdown properly wh…
  src/shared/nested-dropdown-list/nested-dropdown-list.tsx
Labels: bug

#358 Refine time slot bar and introducing minified variant
  src/time-slot-bar/time-slot-bar.styles.tsx
  src/time-slot-bar/time-slot-bar.tsx
  src/time-slot-bar/types.ts
  src/time-slot-week-view/time-slot-week-days.tsx
  stories/time-slot-bar/props-table.tsx
  stories/time-slot-bar/time-slot-bar.stories.mdx
Labels: enhancement

#365 [MOL-14279][HFAH]To enhance box container for HDB car parking pages.
  src/box-container/box-container.styles.tsx
  src/box-container/box-container.tsx
Labels: enhancement

#377 Ensure filter item is expanded in mobile
  src/filter/filter-item.tsx
  tests/filter/filter.spec.tsx
Labels: bug

#376 Slider
  package-lock.json
  package.json
  src/form/form-range-slider.tsx
  src/form/form-slider.tsx
  src/form/index.ts
  src/form/types.ts
  src/input-range-slider/index.ts
  src/input-range-slider/input-range-slider.styles.ts
  src/input-range-slider/input-range-slider.tsx
  src/input-range-slider/types.ts
  src/input-slider/index.ts
  src/input-slider/input-slider.tsx
  src/input-slider/types.ts
  stories/form/form-range-slider/form-range-slider.mdx
  stories/form/form-range-slider/form-range-slider.stories.mdx
  stories/form/form-range-slider/form-range-slider.stories.tsx
  stories/form/form-range-slider/props-table.tsx
  stories/form/form-slider/form-slider.mdx
  stories/form/form-slider/form-slider.stories.mdx
  stories/form/form-slider/form-slider.stories.tsx
  stories/form/form-slider/props-table.tsx
  tests/input-range-slider/input-range-slider.spec.tsx
  tests/input-slider/input-slider.spec.tsx
Labels: enhancement

#381 Fix ErrorDisplay lighthouse warning
  src/error-display/error-display-data.tsx
  src/error-display/helper.ts
  src/error-display/index.ts
Labels: enhancement

#380 Fix NestedMultiSelect error when selected key path does not match options
  src/input-nested-multi-select/input-nested-multi-select.tsx
Labels: bug

#386 Update broken links
  README.md
  stories/data-table/props-table.tsx
  stories/divider/props-table.tsx
  stories/footer/props-table.tsx
  stories/form/form-input-group/props-table.tsx
  stories/form/form-masked-input/props-table.tsx
  stories/getting-started/themes-props-table.tsx
  stories/navbar/props-table.tsx
  stories/notification-banner/props-table.tsx
  stories/otp-input/props-table.tsx
Labels: documentation

#378 Create Tab component
  src/index.ts
  src/shared/clickable-icon/clickable-icon.style.tsx
  src/shared/fade-wrapper/fade-wrapper.style.tsx
  src/shared/fade-wrapper/fade-wrapper.tsx
  src/shared/fade-wrapper/index.ts
  src/shared/fade-wrapper/types.ts
  src/tab/index.ts
  src/tab/tab-context.tsx
  src/tab/tab-item.tsx
  src/tab/tab-link-chain.style.tsx
  src/tab/tab-link-chain.tsx
  src/tab/tab.style.tsx
  src/tab/tab.tsx
  src/tab/types.ts
  stories/tab/doc-elements.tsx
  stories/tab/props-table.tsx
  stories/tab/tab.mdx
  stories/tab/tab.stories.tsx
  tests/tab/tab.spec.tsx
Labels: enhancement
