Repository LifeSG/react-design-system, pull requests merged in 2023-07, with the labels that each got.

#229 [v1] Update react-icons docs link
  stories/icon/icon.stories.mdx
Labels: documentation

#230 Remove migration docs
  MIGRATION.md
  README.md
Labels: documentation

#226 File upload part 6 misc
  package-lock.json
  package.json
  src/file-upload/file-item-edit.tsx
  src/file-upload/file-list-item/file-list-item-thumbnail.tsx
  src/file-upload/file-list-item/file-list-item.styles.tsx
  src/file-upload/file-list-item/file-list-item.tsx
  src/file-upload/file-list.styles.tsx
  src/file-upload/file-list.tsx
  src/file-upload/file-upload.styles.tsx
  src/file-upload/file-upload.tsx
  src/file-upload/types.ts
  src/image-button/image-button.tsx
  src/navbar/brand.tsx
  src/shared/image-with-fallback/image-with-fallback.tsx
  src/shared/progress-bar/progress-bar.tsx
  stories/file-upload/file-upload.stories.mdx
  stories/file-upload/props-table.tsx
  tests/file-upload/file-upload.spec.tsx
Labels: enhancement

#233 Preserve text caret position in formatted input fields
  src/input-group/input-group-list-addon.tsx
  src/input-group/input-group.tsx
  src/input/input.tsx
  src/phone-number-input/phone-number-input.tsx
  src/unit-number/unit-number-input.tsx
  src/util/index.ts
  src/util/use-next-input-state.ts
  tests/input/input.spec.tsx
  tests/phone-number-input/phone-number-input.spec.tsx
  tests/unit-number/unit-number.spec.tsx
Labels: bug

#235 Merge FileUpload long lived
  package-lock.json
  package.json
  src/file-upload/context.tsx
  src/file-upload/custom-sensors.tsx
  src/file-upload/dropzone.styles.tsx
  src/file-upload/dropzone.tsx
  src/file-upload/file-item-edit.styles.tsx
  src/file-upload/file-item-edit.tsx
  src/file-upload/file-list-item/file-list-item-thumbnail.tsx
  src/file-upload/file-list-item/file-list-item.styles.tsx
  src/file-upload/file-list-item/file-list-item.tsx
  src/file-upload/file-list-item/index.ts
  src/file-upload/file-list-item/types.ts
  src/file-upload/file-list.styles.tsx
  src/file-upload/file-list.tsx
  src/file-upload/file-upload.styles.tsx
  src/file-upload/file-upload.tsx
  src/file-upload/helper.ts
  src/file-upload/index.ts
  src/file-upload/types.ts
  src/image-button/image-button.tsx
  src/index.ts
  src/navbar/brand.tsx
  src/shared/image-with-fallback/image-with-fallback.tsx
  src/shared/progress-bar/index.ts
  src/shared/progress-bar/progress-bar.tsx
  src/util/string-helper.ts
  stories/file-upload/file-upload.stories.mdx
  stories/file-upload/props-table.tsx
  tests/file-upload/file-upload.spec.tsx
Labels: enhancement

#232 Pill Component
  src/pill/index.ts
  src/pill/pill.style.tsx
  src/pill/pill.tsx
  src/pill/types.ts
  stories/pill/doc-elements.tsx
  stories/pill/pill.stories.mdx
  stories/pill/props-table.tsx
  tests/pill/pill.spec.tsx
Labels: enhancement

#238 Add onFocus callbacks to date and time inputs, and update Filter examples
  src/calendar/calendar.tsx
  src/date-input/date-input.tsx
  src/date-input/types.ts
  src/date-range-input/date-range-input.tsx
  src/date-range-input/types.ts
  src/filter/filter-item.tsx
  src/shared/internal-calendar/animated-internal-calendar.style.tsx
  src/shared/internal-calendar/internal-calendar.style.tsx
  src/time-range-picker/time-range-picker.tsx
  src/time-range-picker/types.ts
  src/timepicker/timepicker.tsx
  src/timepicker/types.ts
  stories/filter/doc-elements.tsx
  stories/filter/filter-addons.stories.mdx
  stories/filter/filter.stories.mdx
  stories/form/form-date-input/props-table.tsx
  stories/form/form-date-range-input/props-table.tsx
  stories/form/form-time-range-picker/props-table.tsx
  stories/form/form-timepicker/props-table.tsx
Labels: bug, enhancement

#240 Tag component
  src/index.ts
  src/tag/index.ts
  src/tag/tag.style.ts
  src/tag/tag.tsx
  src/tag/types.ts
  stories/pill/pill.stories.mdx
  stories/tag/doc-elements.tsx
  stories/tag/props-table.tsx
  stories/tag/tag.stories.mdx
  tests/tag/tag.spec.tsx
Labels: enhancement

#239 Add predictive input text component
  src/form/form-predictive-text-input.tsx
  src/form/index.ts
  src/form/types.ts
  src/index.ts
  src/input/input.style.tsx
  src/input/input.tsx
  src/input/types.ts
  src/predictive-text-input/index.ts
  src/predictive-text-input/predictive-text-input.tsx
  src/predictive-text-input/types.ts
  src/shared/dropdown-list/dropdown-list.styles.tsx
  src/shared/dropdown-list/dropdown-list.tsx
  src/shared/dropdown-list/types.ts
  src/shared/dropdown-wrapper/dropdown-wrapper.styles.tsx
  src/util/string-helper.ts
  stories/form/form-input/props-table.tsx
  stories/form/form-predictive-text/form-predictive-text-input.stories.mdx
  stories/form/form-predictive-text/mock-fetch-options.ts
  stories/form/form-predictive-text/props-table.tsx
  tests/input-range-select/input-range-select.spec.tsx
Labels: enhancement

#255 Reset border style in radio buttons
  src/radio-button/radio-button.styles.tsx
  src/toggle/toggle.styles.tsx
Labels: bug

#252 Fix scrollable overlay background
  src/overlay/overlay.tsx
Labels: bug

#253 Fix popover rendering out of screen
  src/popover/popover.styles.tsx
  src/popover/popover.tsx
Labels: bug

#245 Remove the default value of expanded and only allow expanded prop to set initial state for Accordion.Item
  src/accordion/accordion-item.tsx
  src/accordion/types.ts
  stories/accordion/props-table.tsx
Labels: bug

#254 Call onChange when unit number is formatted
  src/unit-number/unit-number-input.tsx
Labels: bug

#257 Fix predictive text input bug
  src/predictive-text-input/predictive-text-input.tsx
Labels: bug

#249 Update RangeSelect component
  src/input-range-select/input-range-select.style.tsx
  src/input-range-select/input-range-select.tsx
  src/input/input.style.tsx
Labels: enhancement

#260 [MISC][DH] add `autoDismissTime` prop to Toast component to customize…
  src/toast/toast.tsx
  src/toast/types.ts
  stories/toast/props-table.tsx
  stories/toast/toast.stories.mdx
Labels: enhancement

#262 Display "All selected" in multi-select input
  src/input-multi-select/input-multi-select.tsx
Labels: enhancement

#263 Cater for searching secondary label in lowercase
  src/shared/dropdown-list/dropdown-list.tsx
Labels: bug
