Repository LifeSG/react-design-system, pull requests merged in 2023-11, with the labels that each got.

#346 [MOL-13978][HFAH] Add new variant "fixed-range" for dateRangeInput
  src/date-range-input/date-range-input.tsx
  src/date-range-input/types.ts
  src/shared/internal-calendar/fixed-range/fixed-range-calendar-day-view.tsx
  src/shared/internal-calendar/fixed-range/fixed-range-cell.tsx
  src/shared/internal-calendar/internal-calendar.tsx
  src/shared/internal-calendar/types.ts
  src/util/calendar-helper.ts
  stories/form/form-date-range-input/form-date-range-input.stories.mdx
  stories/form/form-date-range-input/props-table.tsx
Labels: enhancement

#350 Misc theme fixes
  src/countdown-timer/countdown-timer.style.tsx
  src/error-display/error-display.tsx
Labels: bug

#355 [MOL-13885][TK] remove isMobile from withButton
  src/date-input/date-input.tsx
  stories/form/form-date-input/props-table.tsx
Labels: enhancement

#354 [CCUBE-681][DV] DateInput component - NaN display
  src/shared/standalone-date-input/standalone-date-input.tsx
Labels: bug

#342 Fix UI issue in stories when upgrading to v2 stylesheet
  .storybook/preview-head.html
  package-lock.json
  src/shared/dropdown-list/dropdown-list.styles.tsx
  src/shared/nested-dropdown-list/list-item.styles.tsx
  src/shared/nested-dropdown-list/nested-dropdown-list.styles.tsx
  stories/alert/alert.stories.mdx
  stories/storybook-common/api-table/api-table-components.tsx
  tests/utils/calendar-helper.spec.ts
  tests/utils/date-input-helper.spec.ts
Labels: documentation

#362 [MISC][WL] retain horizontal gap in uneditable section
  src/uneditable-section/uneditable-section.styles.tsx
  src/uneditable-section/uneditable-section.tsx
Labels: enhancement

#364 Fix unscrollable page when overlay is unmounted
  src/overlay/overlay.tsx
Labels: bug

#361 Fix select onblur
  src/input-multi-select/input-multi-select.tsx
  src/input-multi-select/types.ts
  src/input-select/input-select.tsx
  src/input-select/types.ts
Labels: bug
