Repository LifeSG/react-design-system, pull requests merged in 2024-05, with the labels that each got.

#461 Fix icon shrinking if button content requires more space
  src/button-with-icon/button-with-icon.style.tsx
Labels: bug

#466 [RBS-1266] Update notification banner component
  src/notification-banner/notification-banner.styles.tsx
  src/notification-banner/notification-banner.tsx
  src/notification-banner/types.ts
  stories/notification-banner/doc-elements.tsx
  stories/notification-banner/notification-banner.mdx
  stories/notification-banner/notification-banner.stories.tsx
  stories/notification-banner/props-table.tsx
Labels: enhancement

#463 [RBS-1265][DS] Update Alert component
  src/alert/alert.style.tsx
  src/alert/alert.tsx
  src/alert/types.ts
  stories/alert/alert.mdx
  stories/alert/alert.stories.tsx
  stories/alert/props-table.tsx
  tests/alert/alert.spec.tsx
  tests/uneditable-section/uneditable-section.spec.tsx
Labels: enhancement

#472 [RBS-1265][DS] minor styling fix for alert actionlink
  src/alert/alert.style.tsx
  src/alert/alert.tsx
  stories/alert/alert.stories.tsx
  stories/notification-banner/notification-banner.stories.tsx
Labels: bug

#473 [MISC][WL] allow more characters in select label before ellipsis
  src/shared/dropdown-wrapper/dropdown-wrapper.styles.tsx
Labels: bug

#474 Create component to apply default HTML styles for JSX children
  src/alert/alert.style.tsx
  src/file-upload/file-upload.styles.tsx
  src/index.ts
  src/markup/index.ts
  src/markup/markup.style.tsx
  src/markup/markup.tsx
  src/markup/types.ts
  src/popover-v2/popover.styles.tsx
  src/shared/html-content/html-content.ts
  stories/markup/markup.mdx
  stories/markup/markup.stories.tsx
  stories/markup/props-table.tsx
Labels: enhancement

#475 small change in maxCollapsedHeight documentation and stories to clarify requirements
  stories/notification-banner/notification-banner.mdx
  stories/notification-banner/notification-banner.stories.tsx
Labels: documentation
