Repository LifeSG/react-design-system, pull requests merged in 2024-07, with the labels that each got.

#496 Document clear button for InputGroup
  stories/form/form-input-group/form-input-group.mdx
  stories/form/form-input-group/form-input-group.stories.tsx
  stories/form/form-phone-number-input/form-phone-number-input.mdx
  stories/form/form-phone-number-input/form-phone-number-input.stories.tsx
  stories/text/b-advanced.mdx
Labels: documentation

#497 Updated colour of form label and textarea counter to match Figma
  src/form/form-label.style.tsx
  src/input-textarea/textara-counter.style.tsx
Labels: bug

#494 CCUBE-1414: Add loading indicator to e-signature
  src/e-signature/e-signature-canvas.tsx
  src/e-signature/e-signature.styles.ts
  src/e-signature/e-signature.tsx
  src/e-signature/types.ts
  stories/form/form-e-signature/form-e-signature.mdx
  stories/form/form-e-signature/form-e-signature.stories.tsx
  stories/form/form-e-signature/props-table.tsx
  tests/e-signature/e-signature.spec.tsx
Labels: enhancement

#501 Date input tests
  .gitignore
  .storybook/manager.js
  e2e/date-input/__screenshots__/chrome-mobile/empty-input--calendar-closed.png
  e2e/date-input/__screenshots__/chrome-mobile/empty-input--calendar-hover.png
  e2e/date-input/__screenshots__/chrome-mobile/empty-input--calendar-open.png
  e2e/date-input/__screenshots__/chrome-mobile/empty-input--calendar-select-date.png
  e2e/date-input/__screenshots__/chrome-mobile/empty-input--mount.png
  e2e/date-input/__screenshots__/chrome-mobile/empty-input-without-button--calendar-open.png
  e2e/date-input/__screenshots__/chromium/empty-input--calendar-closed.png
  e2e/date-input/__screenshots__/chromium/empty-input--calendar-hover.png
  e2e/date-input/__screenshots__/chromium/empty-input--calendar-open.png
  e2e/date-input/__screenshots__/chromium/empty-input--calendar-select-date.png
  e2e/date-input/__screenshots__/chromium/empty-input--mount.png
  e2e/date-input/__screenshots__/chromium/empty-input-without-button--calendar-open.png
  e2e/date-input/date-input.e2e.spec.ts
  jest.config.js
  package-lock.json
  package.json
  playwright.config.ts
  src/shared/internal-calendar/calendar-dropdown.tsx
  stories/form/form-date-input/form-date-input.e2e.stories.tsx
  tests/date-input/date-input.spec.tsx
  tests/footer/footer.spec.tsx
  tests/time-slot-bar-week/time-slot-bar-week.spec.tsx
  tests/time-slot-week-view/time-slot-week-view.spec.tsx
  tests/utils/__snapshots__/calendar-helper.spec.ts.snap
Labels: tests

#499 [MOL-15988][DS] fix for standalone-date-input displaying NaN for invalid dates
  src/shared/standalone-date-input/standalone-date-input.tsx
Labels: bug

#502 Fix text wrap in `UneditableSection.Item`
  src/uneditable-section/section-item.styles.tsx
Labels: bug

#505 [MOL-16081][KE] Added `disabled` variant in timeline component
  src/timeline/timeline.style.tsx
  src/timeline/types.ts
  stories/timeline/props-table.tsx
  stories/timeline/timeline.stories.tsx
Labels: enhancement

#506 [BOOKINGSG-5584][RT] Fix date input color after selection in mobile stays gray
  src/date-input/date-input.tsx
Labels: bug

#504 [MOL-16080][ZX] update boxcontainer to able to click on header
  src/box-container/box-container.styles.tsx
  src/box-container/box-container.tsx
  src/box-container/types.ts
  stories/box-container/props-table.tsx
Labels: enhancement

#507 Fix breadcrumb flash
  .eslintrc
  e2e/breadcrumb/__screenshots__/chrome-mobile/long--mount.png
  e2e/breadcrumb/__screenshots__/chrome-mobile/long--scroll.png
  e2e/breadcrumb/__screenshots__/chrome-mobile/short--mount.png
  e2e/breadcrumb/__screenshots__/chromium/long--mount.png
  e2e/breadcrumb/__screenshots__/chromium/short--mount.png
  e2e/breadcrumb/breadcrumb.e2e.spec.ts
  src/breadcrumb/breadcrumb.tsx
  src/util/index.ts
  src/util/use-event.ts
  src/util/use-isomorphic-layout-effect.ts
  stories/breadcrumb/breadcrumb.e2e.stories.tsx
  stories/breadcrumb/breadcrumb.stories.tsx
  stories/breadcrumb/props-table.tsx
Labels: bug

#511 [MOL-16130][ZX] update title of box container to accept JSX.Element
  src/box-container/types.ts
  stories/box-container/props-table.tsx
Labels: enhancement

#510 Make it easier to reset spacing in `Toggle` composite section
  src/toggle/toggle.styles.tsx
  src/toggle/toggle.tsx
Labels: enhancement

#514 Fix calendar opening on disabled date picker
  src/date-input/date-input.tsx
  src/date-range-input/date-range-input.tsx
  tests/date-input/date-input.spec.tsx
Labels: bug

#515 Revert toggle width
  src/toggle/toggle.styles.tsx
Labels: bug

#516 Update modal button
  src/modal/modal-box.styles.tsx
  src/modal/modal-box.tsx
  stories/modal/modal.mdx
  stories/modal/modal.stories.tsx
Labels: enhancement

#519 Mol 15870 - Add OneService theme
  .storybook/preview.ts
  src/spec/color-spec/oneservice-color-set.ts
  src/spec/text-spec/oneservice-text-style-set.ts
  src/theme/color-theme-helper.ts
  src/theme/index.ts
  src/theme/text-theme-helper.ts
  src/theme/types.ts
  stories/color/oneservice-color.mdx
  stories/getting-started/themes.mdx
  stories/text/c-base-collection.mdx
  stories/text/collection-doc-elements.tsx
  stories/text/d-oneservice-collection.mdx
Labels: enhancement

#509 Fix select dropdown getting cut off by parent
  src/date-input/date-input.tsx
  src/date-range-input/date-range-input.tsx
  src/input-select/input-select.tsx
  src/input-select/types.ts
  src/shared/dropdown-list-v2/dropdown-label.styles.tsx
  src/shared/dropdown-list-v2/dropdown-label.tsx
  src/shared/dropdown-list-v2/dropdown-list-state.tsx
  src/shared/dropdown-list-v2/dropdown-list.styles.tsx
  src/shared/dropdown-list-v2/dropdown-list.tsx
  src/shared/dropdown-list-v2/dropdown-search.styles.tsx
  src/shared/dropdown-list-v2/dropdown-search.tsx
  src/shared/dropdown-list-v2/expandable-element.styles.tsx
  src/shared/dropdown-list-v2/expandable-element.tsx
  src/shared/dropdown-list-v2/index.ts
  src/shared/dropdown-list-v2/types.ts
  src/shared/dropdown-wrapper/element-with-dropdown.styles.tsx
  src/shared/dropdown-wrapper/element-with-dropdown.tsx
  src/shared/dropdown-wrapper/types.ts
  src/shared/input-wrapper/input-wrapper.tsx
  src/shared/internal-calendar/calendar-dropdown.style.tsx
  src/shared/internal-calendar/calendar-dropdown.tsx
  src/shared/internal-calendar/types.ts
  src/util/index.ts
  src/util/use-mount.ts
  src/util/use-previous.ts
  stories/form/form-select/form-select.mdx
  stories/form/form-select/form-select.stories.tsx
  stories/form/form-select/props-table.tsx
  tests/date-input/date-input.spec.tsx
  tests/input-select/input-select.spec.tsx
Labels: enhancement

#520 Fix multiselect dropdown getting cut off
  src/input-multi-select/input-multi-select.tsx
  src/input-multi-select/types.ts
  src/input-select/input-select.tsx
  src/shared/dropdown-list-v2/dropdown-list.styles.tsx
  src/shared/dropdown-list-v2/dropdown-list.tsx
  src/shared/dropdown-list-v2/expandable-element.tsx
  src/shared/input-wrapper/input-wrapper.tsx
  stories/form/form-multi-select/props-table.tsx
  stories/form/form-select/props-table.tsx
  tests/input-multi-select/input-multi-select.spec.tsx
Labels: enhancement

#522 [TOAST][WL] left align toast content in mobile
  src/toast/toast.styles.tsx
Labels: bug

#513 RBS-1395 Create Download File component
  package-lock.json
  src/file-download/file-download.styles.tsx
  src/file-download/file-download.tsx
  src/file-download/file-list-card/file-list-card.styles.tsx
  src/file-download/file-list-card/file-list-card.tsx
  src/file-download/file-list-card/index.ts
  src/file-download/file-list-card/types.ts
  src/file-download/index.ts
  src/file-download/types.ts
  src/file-upload/file-list-item/file-list-item.styles.tsx
  src/index.ts
  src/util/string-helper.ts
  stories/file-download/file-download.mdx
  stories/file-download/file-download.stories.tsx
  stories/file-download/props-table.tsx
Labels: enhancement
