Repository LifeSG/react-design-system, pull requests merged in 2024-06, with the labels that each got.

#478 Update font color for masked value in `UneditableSection`
  src/uneditable-section/section-item.styles.tsx
Labels: bug

#480 [MISC][SW] regen packagelock with node 18
  .eslintrc
  package-lock.json
  package.json
  rollup.config.js
Labels: enhancement

#484 fix vulns
  .eslintrc
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  stories/text/a-intro.mdx
Labels: documentation, enhancement

#485 Update `Text` documentation
  stories/text/b-advanced.mdx
  stories/text/b-advanced.stories.tsx
  stories/text/doc-elements.tsx
Labels: documentation

#482 Adding action button and ammending typings for title and label for the toast
  src/toast/toast.styles.tsx
  src/toast/toast.tsx
  src/toast/types.ts
  stories/toast/props-table.tsx
  stories/toast/toast.mdx
  stories/toast/toast.stories.tsx
Labels: enhancement

#477 Update Toggle to cater for composite Section
  src/toggle/toggle.styles.tsx
  src/toggle/toggle.tsx
  src/toggle/types.ts
  stories/toggle/doc-elements.tsx
  stories/toggle/props-table.tsx
  stories/toggle/toggle-4-removable.mdx
  stories/toggle/toggle-4-removable.stories.tsx
  stories/toggle/toggle-5-composite-section.mdx
  stories/toggle/toggle-5-composite-section.stories.tsx
  stories/toggle/toggle-6-examples.mdx
  stories/toggle/toggle-6-examples.stories.tsx
  stories/toggle/toggle.mdx
  stories/toggle/toggle.stories.tsx
Labels: enhancement

#486 Give precedence to mobile elements when hiding menu button
  src/navbar/navbar.tsx
  tests/navbar/navbar.spec.tsx
Labels: bug

#479 Add small variant to InputSelect
  src/form/form-multi-select.tsx
  src/form/form-select.tsx
  src/input-multi-select/input-multi-select.tsx
  src/input-multi-select/types.ts
  src/input-select/input-select.tsx
  src/input-select/types.ts
  src/shared/dropdown-list/dropdown-list.styles.tsx
  src/shared/dropdown-list/dropdown-list.tsx
  src/shared/dropdown-list/dropdown-search.styles.tsx
  src/shared/dropdown-list/dropdown-search.tsx
  src/shared/dropdown-list/types.ts
  src/shared/dropdown-wrapper/dropdown-wrapper.styles.tsx
  src/shared/dropdown-wrapper/dropdown-wrapper.tsx
  src/shared/dropdown-wrapper/types.ts
  src/shared/input-wrapper/input-wrapper.tsx
  stories/form/form-multi-select/form-multi-select.mdx
  stories/form/form-multi-select/form-multi-select.stories.tsx
  stories/form/form-multi-select/props-table.tsx
  stories/form/form-select/form-select.mdx
  stories/form/form-select/form-select.stories.tsx
  stories/form/form-select/props-table.tsx
Labels: enhancement

#490 [MOL-15775][AM] Remove event.prevant default to fix the selection wor…
  src/toggle/toggle.tsx
Labels: bug

#489 Amended the touch area of the cross button & button styles for the toast enhancements
  src/toast/toast.styles.tsx
Labels: enhancement

#488 Ccube 1414
  package-lock.json
  package.json
  src/e-signature/e-signature-canvas.tsx
  src/e-signature/e-signature.styles.ts
  src/e-signature/e-signature.tsx
  src/e-signature/index.ts
  src/e-signature/types.ts
  src/form/form-e-signature.tsx
  src/form/index.ts
  src/form/types.ts
  stories/form/form-e-signature/doc-elements.ts
  stories/form/form-e-signature/form-e-signature.mdx
  stories/form/form-e-signature/form-e-signature.stories.tsx
  stories/form/form-e-signature/props-table.tsx
  tests/e-signature/e-signature.spec.tsx
Labels: enhancement

#492 Add stories for two tier nested select
  stories/form/form-nested-multi-select/form-nested-multi-select.stories.tsx
  stories/form/form-nested-select/form-nested-select.stories.tsx
  stories/form/form-nested-select/nested-data-list.ts
Labels: documentation

#493 `DateInput`: fix dismiss behaviour, enhance focus and blur handling
  src/date-input/date-input.tsx
  src/date-range-input/date-range-input.tsx
  src/shared/dropdown-wrapper/element-with-dropdown.tsx
  src/shared/input-wrapper/input-wrapper.tsx
  src/shared/standalone-date-input/standalone-date-input.tsx
  stories/filter/doc-elements.tsx
Labels: bug
