Repository LifeSG/react-design-system, pull requests merged in 2025-04, with the labels that each got.

#661 Commportal-195: update border-selected for PA
  src/theme/colour-primitive/specs/pa-colour-set.ts
  src/theme/colour-semantic/specs/pa-semantic-tokens.ts
  src/theme/font-spec/specs/pa-font-spec-set.ts
Labels: enhancement

#672 [COMMPORTAL-195][SW] update pa semantic tokens
  src/theme/colour-semantic/specs/pa-semantic-tokens.ts
Labels: enhancement

#671 [MISC][NT] Update all ref.current for v2 to check for nullish
  src/date-input/date-input.tsx
  src/date-range-input/date-range-input.tsx
  src/drawer/drawer.tsx
  src/e-signature/e-signature-canvas.tsx
  src/e-signature/e-signature.tsx
  src/file-upload/dropzone.tsx
  src/file-upload/file-item-edit.tsx
  src/fullscreen-image-carousel/fullscreen-image-carousel.tsx
  src/input-group/input-group-list-addon.tsx
  src/input-multi-select/input-multi-select.tsx
  src/input-nested-multi-select/input-nested-multi-select.tsx
  src/input-nested-select/input-nested-select.tsx
  src/input-range-select/input-range-select.tsx
  src/input-select/input-select.tsx
  src/select-histogram/select-histogram.tsx
  src/shared/dropdown-list-v2/dropdown-list.tsx
  src/shared/dropdown-list-v2/nested-dropdown-list.tsx
  src/shared/dropdown-list/dropdown-list.tsx
  src/shared/internal-calendar/calendar-manager.tsx
  src/shared/internal-calendar/internal-calendar.tsx
  src/shared/standalone-date-input/standalone-date-input.tsx
  src/tab/tab-link-chain.tsx
  src/time-range-picker/combobox-picker/combobox-picker.tsx
  src/time-range-picker/dial-picker/dial-picker.tsx
  src/timepicker/timepicker.tsx
  src/unit-number/unit-number-input.tsx
Labels: enhancement

#673 Export new V3 Text-List
  src/index.ts
Labels: bug

#675 Resolve React 18+ spread key warning in unit tests
  src/shared/dropdown-list-v2/dropdown-list.tsx
  src/shared/dropdown-list-v2/nested-dropdown-list.tsx
Labels: bug

#676 V3 story cleanup
  stories/form/form-custom-field/form-custom-field.stories.tsx
  stories/form/form-label/doc-elements.tsx
  stories/form/form-label/form-label.stories.tsx
  stories/masonry/doc-elements.tsx
  stories/masonry/masonry.stories.tsx
  stories/storybook-common/story-container.tsx
  stories/toggle/toggle-5-composite-section.stories.tsx
Labels: documentation
