Repository LifeSG/react-design-system, pull requests merged in 2025-07, with the labels that each got.

#718 Add unit tests for date range component
  tests/common/waitForElementRemoved.ts
  tests/date-range-input/date-range-input.spec.tsx
  tests/date-range-input/fixed-range-date-range-input.spec.tsx
  tests/date-range-input/week-date-range-input.spec.tsx
Labels: tests

#720 [CCUBE-1833][XY] Add border to drop shadow components
  src/card/card.style.tsx
  src/navbar/menu.styles.tsx
  src/navbar/navbar.styles.tsx
  src/smart-app-banner/smart-app-banner.styles.ts
Labels: bug

#727 Fix codemod mapping for small Hyperlink
  codemods/migrate-text/data.ts
Labels: bug

#729 [MISC][Viv] Checkbox a11y improvements (keyboard navigation, option to set custom id to link to label)
  src/checkbox/checkbox.style.tsx
  src/checkbox/checkbox.tsx
  stories/checkbox/checkbox.stories.tsx
  stories/checkbox/doc-elements.tsx
Labels: enhancement, a11y

#730 [MISC][JH] tag changes for accessibility
  src/button-with-icon/button-with-icon.tsx
  src/tag/tag.tsx
Labels: enhancement, a11y

#735 Fix masthead dark mode
  package-lock.json
  package.json
  rollup.config.js
  scripts/build-util.js
  src/masthead/masthead.tsx
  stories/masthead/masthead.mdx
  stories/navbar/navbar.mdx
Labels: bug

#734 Accordion a11y (part 2)
  src/accordion/accordion-context.tsx
  src/accordion/accordion-item.style.tsx
  src/accordion/accordion-item.tsx
  src/accordion/accordion.style.tsx
  src/accordion/accordion.tsx
  src/accordion/types.ts
  src/theme/colour-semantic/specs/a11yplayground-semantic-tokens.ts
  src/theme/colour-semantic/specs/lifesg-semantic-tokens.ts
  src/theme/colour-semantic/specs/pa-semantic-tokens.ts
  stories/accordion/accordion.mdx
  stories/accordion/accordion.stories.tsx
  stories/accordion/props-table.tsx
  tests/accordion/accordion.spec.tsx
Labels: enhancement, a11y

#732 [MISC][XY] Accessibility improvements to Navbar
  src/navbar/brand.styles.tsx
  src/navbar/brand.tsx
  src/navbar/drawer.styles.tsx
  src/navbar/drawer.tsx
  src/navbar/navbar-items.tsx
  src/navbar/navbar.tsx
  src/navbar/types.ts
  stories/navbar/props-table.tsx
Labels: enhancement, a11y

#738 [BOOKINGSG-7788][NT] Inert on filter items in desktop view to prevent…
  src/filter/filter-item.tsx
Labels: bug, a11y

#741 Fixed FilterItem render in mobile view
  src/filter/addons/filter-item-checkbox.styles.tsx
  src/filter/addons/filter-item-checkbox.tsx
  src/filter/filter-item.tsx
Labels: bug

#742 [BOOKINGSG-7788][ NT] Added min width for toggle button
  src/filter/addons/filter-item-checkbox.styles.tsx
Labels: enhancement

#743 Update OneService colour tokens, fix `info-40`
  .storybook/preview.ts
  src/theme/colour-primitive/specs/bookingsg-colour-set.ts
  src/theme/colour-primitive/specs/ccube-colour-set.ts
  src/theme/colour-primitive/specs/lifesg-colour-set.ts
  src/theme/colour-primitive/specs/mylegacy-colour-set.ts
  src/theme/colour-primitive/specs/oneservice-colour-set.ts
  src/theme/colour-primitive/specs/pa-colour-set.ts
  src/theme/colour-primitive/specs/rbs-colour-set.ts
  src/theme/colour-primitive/specs/supportgowhere-colour-set.ts
  stories/theme/colour/g-colour-oneservice.mdx
Labels: bug, enhancement

#747 Adjust breakpoints
  src/theme/breakpoint/specs/default-breakpoint-set.ts
  stories/theme/breakpoint/a-breakpoint-introduction.mdx
  tests/layout/layout-coldiv.spec.tsx
Labels: enhancement

#744 Sidenav a11y
  src/sidenav/sidenav-context.tsx
  src/sidenav/sidenav-drawer-item.tsx
  src/sidenav/sidenav-item.styles.tsx
  src/sidenav/sidenav-item.tsx
  src/sidenav/sidenav.styles.tsx
  src/sidenav/sidenav.tsx
  src/sidenav/types.ts
  stories/sidenav/props-table.tsx
  tests/sidenav/sidenav.spec.tsx
Labels: enhancement, a11y

#754 [COMMPORTAL-353][SW] add custom label for Filter Done button
  src/filter/filter.tsx
  src/filter/types.ts
  stories/filter/props-table.tsx
Labels: enhancement

#748 [BOOKINGSG-7816][JZ] [DS] Update styling of NotificationBanner component
  package-lock.json
  src/notification-banner/notification-banner.styles.tsx
  src/notification-banner/notification-banner.tsx
  src/notification-banner/types.ts
  stories/notification-banner/notification-banner.mdx
  stories/notification-banner/notification-banner.stories.tsx
  stories/notification-banner/props-table.tsx
Labels: enhancement, a11y

#737 [MISC][ZY] Improve a11y for Form.Input
  src/form/form-date-input.tsx
  src/form/form-date-range-input.tsx
  src/form/form-input.tsx
  src/form/form-label.style.tsx
  src/form/form-label.tsx
  src/form/form-wrapper.tsx
  src/input/input.tsx
  stories/form/form-custom-field/form-custom-field.mdx
  stories/form/form-custom-field/form-custom-field.stories.tsx
Labels: enhancement, a11y

#733 [MISC][Viv] LocalNav a11y improvements
  src/local-nav/internal-types.tsx
  src/local-nav/local-nav-dropdown/local-nav-dropdown.styles.tsx
  src/local-nav/local-nav-dropdown/local-nav-dropdown.tsx
  src/local-nav/local-nav-menu/local-nav-menu.styles.tsx
  src/local-nav/local-nav-menu/local-nav-menu.tsx
  src/local-nav/types.ts
  stories/local-nav/doc-elements.tsx
  stories/local-nav/local-nav.stories.tsx
  stories/local-nav/props-table.tsx
  tests/local-nav/local-nav.spec.tsx
Labels: a11y
