Repository LifeSG/react-design-system, pull requests merged in 2025-09, with the labels that each got.

#787 [MOL-19180][LP] Accessibility enhancements for Drawer
  src/drawer/drawer.styles.tsx
  src/drawer/drawer.tsx
  src/overlay/overlay.tsx
  stories/drawer/drawer.stories.tsx
Labels: enhancement, a11y

#828 [OTP][SW] update styling of OTP
  src/otp-input/otp-input.styles.tsx
  src/otp-input/otp-input.tsx
Labels: type: enhancement

#830 Prefix scrollbar selectors to fix missing styles
  src/data-table/data-table.styles.tsx
  src/popover-v2/popover.styles.tsx
  src/popover/popover.styles.tsx
  src/shared/dropdown-list-v2/dropdown-list.styles.tsx
  src/shared/dropdown-list/dropdown-list.styles.tsx
  src/shared/fade-wrapper/fade-wrapper.style.tsx
Labels: type: bug

#832 [CCUBE-1959][XY] Add IMDA theme
  .storybook/preview-head.html
  .storybook/preview.ts
  src/theme/colour-primitive/specs/imda-colour-set.ts
  src/theme/colour-primitive/theme-helper.ts
  src/theme/colour-semantic/theme-helper.ts
  src/theme/font-spec/specs/imda-font-spec-set.ts
  src/theme/font-spec/theme-helper.ts
  src/theme/font/specs/imda-font-set.ts
  src/theme/font/theme-helper.ts
  src/theme/index.ts
  src/theme/types.ts
  stories/getting-started/installation.mdx
  stories/theme/b-theme-introduction.mdx
  stories/theme/colour/a-colour-introduction.mdx
  stories/theme/colour/k-colour-imda.mdx
  stories/theme/font/a-font-introduction.mdx
  stories/theme/font/g-font-imda.mdx
Labels: type: enhancement

#756 Modalv2
  src/index.ts
  src/modal-v2/index.ts
  src/modal-v2/modal-context.tsx
  src/modal-v2/modal-v2.styles.tsx
  src/modal-v2/modal-v2.tsx
  src/modal-v2/slots/card.tsx
  src/modal-v2/slots/close-button.tsx
  src/modal-v2/slots/content.tsx
  src/modal-v2/slots/index.tsx
  src/modal-v2/slots/slot-styles.tsx
  src/modal-v2/types.ts
  src/modal/modal.styles.tsx
  src/modal/modal.tsx
  src/modal/types.ts
  src/overlay/overlay.styles.tsx
  src/overlay/overlay.tsx
  src/shared/hooks/index.tsx
  src/shared/hooks/useViewport.tsx
  stories/modal-v2/modal-v2.mdx
  stories/modal-v2/modal-v2.stories.tsx
  stories/modal-v2/props-table.tsx
  stories/modal-v2/style-tokens-table.tsx
Labels: type: enhancement, a11y

#835 ModalV2 Footer and slot styling
  src/modal-v2/index.ts
  src/modal-v2/slots/card.tsx
  src/modal-v2/slots/close-button.tsx
  src/modal-v2/slots/content.tsx
  src/modal-v2/slots/footer.tsx
  src/modal-v2/slots/index.tsx
  src/modal-v2/slots/slot-styles.tsx
  src/modal-v2/types.ts
  stories/modal-v2/doc-elements.tsx
  stories/modal-v2/modal-v2.mdx
  stories/modal-v2/modal-v2.stories.tsx
  stories/modal-v2/props-table.tsx
  stories/modal/modal.mdx
  tests/modal-v2/modal-v2.spec.tsx
Labels: type: enhancement

#837 Update FilterItemCheckbox to support checkbox in tablet/mobile + Make minimizing optional
  src/filter/addons/filter-item-checkbox.styles.tsx
  src/filter/addons/filter-item-checkbox.tsx
  src/filter/types.ts
  stories/filter/addon-props-table.tsx
  stories/filter/filter-addons.stories.tsx
Labels: type: enhancement
