Repository LifeSG/react-design-system, pull requests merged in 2025-08, with the labels that each got.

#759 [MOL-19033][RP] Migrate the footer changes for v2 to v3
  src/footer/footer-download-app.style.tsx
  src/footer/footer-download-app.tsx
  src/footer/footer-helper.ts
  src/footer/footer-resource-addon.styles.tsx
  src/footer/footer-resource-addon.tsx
  src/footer/footer.style.tsx
  src/footer/footer.tsx
  src/footer/types.ts
  stories/footer/footer.mdx
  stories/footer/footer.stories.tsx
  stories/footer/props-table.tsx
Labels: enhancement

#776 [MOL-19265][JC] add expandCollapseClickCallback to Accordion
  src/accordion/accordion.tsx
  src/accordion/types.ts
  stories/accordion/props-table.tsx
Labels: enhancement

#770 Bookingsg 7851: Make Footer Accessible
  src/footer/footer-download-app.tsx
  src/footer/footer-helper.ts
Labels: enhancement, a11y

#777 [BOOKINGSG-7853][NT] Added default aria-hidden to pill icon
  src/pill/pill.tsx
Labels: enhancement, a11y

#775 [BOOKINGSG-7852][NT] Added accessibility to progress indicator component
  src/progress-indicator/progress-indicator.tsx
Labels: enhancement, a11y

#774 [COMMPORTAL-353][SW] update props for custom labels in Filter
  src/filter/filter.tsx
  src/filter/types.ts
  src/link-list/components/link-list-eager.tsx
  src/link-list/components/link-list-lazy.tsx
  src/link-list/internal-types.ts
  src/link-list/link-list.tsx
  stories/filter/props-table.tsx
  stories/link-list/link-list.stories.tsx
  stories/link-list/props-table.tsx
  tests/link-list/link-list.spec.tsx
Labels: enhancement

#780 [CCUBE-1885][P] add nav, footer logo, update disclaimer and copyright text for sgw
  src/footer/footer-disclaimer-links-data.tsx
  src/footer/footer-helper.ts
  src/footer/footer.tsx
  src/footer/types.ts
  src/navbar/navbar-logo-data.ts
  stories/footer/footer.mdx
  stories/footer/footer.stories.tsx
  stories/footer/props-table.tsx
  tests/footer/footer.spec.tsx
Labels: enhancement

#785 Update shadow unit tests for SC6
  tests/theme/theme-shadow.spec.tsx
Labels: tests

#764 [MOL-19016][GW] Add avatar navbar story
  stories/navbar/doc-elements.tsx
  stories/navbar/navbar.mdx
  stories/navbar/navbar.stories.tsx
Labels: documentation

#781 Bookingsg 7877
  src/file-upload/file-item-edit.tsx
  src/file-upload/file-list-item/file-list-item.tsx
  src/file-upload/file-list.tsx
  src/file-upload/file-upload.tsx
  stories/file-upload/file-upload.stories.tsx
  tests/file-upload/file-upload.spec.tsx
Labels: enhancement, a11y

#788 [MISC][NT] Fixed overlay with aria-hidden when filters are open
  src/filter/filter.styles.tsx
  src/filter/filter.tsx
Labels: bug, a11y

#789 Mol 19139 v2
  src/toggle/toggle.styles.tsx
  src/toggle/toggle.tsx
Labels: bug

#790 Resolve React warnings, fix Typography polymorphism
  src/input-multi-select/input-multi-select.tsx
  src/input-nested-multi-select/input-nested-multi-select.tsx
  src/input-nested-select/input-nested-select.tsx
  src/input-range-select/input-range-select.tsx
  src/input-select/input-select.tsx
  src/modal/modal.styles.tsx
  src/modal/modal.tsx
  src/select-histogram/select-histogram.styles.tsx
  src/select-histogram/select-histogram.tsx
  src/shared/dropdown-list/dropdown-list.styles.tsx
  src/shared/dropdown-list/dropdown-list.tsx
  src/shared/dropdown-wrapper/dropdown-wrapper.styles.tsx
  src/shared/dropdown-wrapper/dropdown-wrapper.tsx
  src/timepicker/timepicker.styles.tsx
  src/timepicker/timepicker.tsx
  src/typography/helper.ts
  src/typography/typography.styles.tsx
  src/typography/typography.tsx
  tests/input-multi-select/input-multi-select.spec.tsx
  tests/input-nested-select/input-nested-select.spec.tsx
  tests/input-select/input-select.spec.tsx
  tests/sidenav/sidenav.spec.tsx
Labels: bug

#755 Improve auto positioning for dropdown elements
  src/date-input/date-input.tsx
  src/date-range-input/date-range-input.tsx
  src/input-multi-select/input-multi-select.tsx
  src/input-nested-multi-select/input-nested-multi-select.tsx
  src/input-nested-select/input-nested-select.tsx
  src/input-select/input-select.tsx
  src/select-histogram/select-histogram.styles.tsx
  src/select-histogram/select-histogram.tsx
  src/shared/dropdown-list-v2/dropdown-list.styles.tsx
  src/shared/dropdown-list-v2/dropdown-list.tsx
  src/shared/dropdown-list-v2/nested-dropdown-list.tsx
  src/shared/dropdown-list-v2/types.ts
  src/shared/dropdown-wrapper/element-with-dropdown.tsx
  src/shared/internal-calendar/calendar-dropdown.tsx
  src/time-range-picker/combobox-picker/combobox-picker.tsx
  src/util/index.ts
  src/util/merge-refs.ts
  tests/input-multi-select/input-multi-select.spec.tsx
  tests/input-select/input-select.spec.tsx
  tests/time-range-picker/time-range-picker.spec.tsx
Labels: bug

#791 Gracefully handle missing icon for ButtonWithIcon
  src/button-with-icon/button-with-icon.tsx
Labels: bug

#795 [MOL-17794][SL] update breakpoints for tablet and desktop
  src/theme/breakpoint/specs/default-breakpoint-set.ts
  tests/layout/layout-coldiv.spec.tsx
Labels: enhancement

#799 [COMMPORTAL-353][SW] feat: add custom clear button label
  src/filter/filter.tsx
  src/filter/types.ts
  stories/filter/props-table.tsx
Labels: enhancement

#800 [MISC][SW] feat: add prop to filter to force mobile view
  src/filter/filter.tsx
  src/filter/types.ts
Labels: enhancement

#802 [BOOKINGSG-7744][LP] Update dropdownWidth
  src/schedule/schedule-header/schedule-header.tsx
Labels: bug

#803 [COMMPORTAL-1004][SW] add callback on opening mobile filter
  src/filter/filter.tsx
  src/filter/types.ts
  stories/filter/props-table.tsx
Labels: enhancement
