Repository LifeSG/react-design-system, pull requests merged in 2025-05, with the labels that each got.

#680 [BOOKINGSG-7092-v2][JZ] Add pending status and its design implementation
  src/timetable/const.ts
  src/timetable/internal-types.ts
  src/timetable/timetable-row/row-bar.tsx
  src/timetable/timetable-row/row-cell.style.tsx
  src/timetable/timetable-row/row-cell.tsx
  src/timetable/timetable.tsx
  src/timetable/types.ts
  stories/timetable/mock-data.tsx
  stories/timetable/props-table.tsx
  stories/timetable/timetable-default-data.tsx
  stories/timetable/timetable-even-days-data.tsx
Labels: enhancement

#678 [BOOKINGSG-7232-v3][JZ] Update color and allow 24 hour rows
  src/timetable/internal-types.ts
  src/timetable/timetable-row/row-bar.tsx
  src/timetable/timetable-row/row-cell.tsx
  src/timetable/timetable.style.tsx
  src/timetable/timetable.tsx
  src/util/time-helper.ts
  stories/timetable/props-table.tsx
  stories/timetable/timetable-default-data.tsx
  stories/timetable/timetable.mdx
  stories/timetable/timetable.stories.tsx
  tests/timetable/timetable.spec.tsx
  tests/utils/time-helper.spec.ts
Labels: enhancement

#677 [BOOKINGSG-7232][JZ] Update color and allow 24 hour rows
  src/timetable/internal-types.ts
  src/timetable/timetable-row/row-bar.tsx
  src/timetable/timetable-row/row-cell.tsx
  src/timetable/timetable.style.tsx
  src/timetable/timetable.tsx
  src/util/time-helper.ts
  stories/timetable/props-table.tsx
  stories/timetable/timetable-default-data.tsx
  stories/timetable/timetable.mdx
  tests/timetable/timetable.spec.tsx
  tests/utils/time-helper.spec.ts
Labels: enhancement

#682 Introduce themed loading spinner
  src/animations/index.ts
  src/animations/loading-spinner/data.json
  src/animations/themed-loading-spinner/themed-loading-spinner.tsx
  stories/animation/1-animations-overview.mdx
  stories/animation/1-animations-overview.stories.tsx
Labels: enhancement

#681 [CCUBE-1755] Introduce component tokens
  src/button/button.style.tsx
  src/theme/components/specs/default-component-token-set.ts
  src/theme/components/specs/pa-component-token-set.ts
  src/theme/components/theme-helper.ts
  src/theme/components/types.ts
  src/theme/index.ts
  src/theme/types.ts
  stories/button/button.mdx
  stories/button/button.stories.tsx
  stories/button/tokens-table.tsx
  tests/layout/mock-theme-data.ts
  tests/theme/mock-theme-data.ts
  tests/typography/mock-theme-data.ts
Labels: enhancement

#687 Fix incorrectly migrated breakpoints
  src/button/button.style.tsx
  src/timeline/timeline.style.tsx
Labels: bug

#685 [CCUBE-1770][HN] Upgrade to Node 22.15.0 and fix vulnerabilities
  .nvmrc
  package-lock.json
  package.json
Labels: enhancement

#689 Enhancements to Tab
  src/tab/tab-link-chain.style.tsx
  src/tab/tab-link-chain.tsx
  src/tab/tab.tsx
  src/tab/types.ts
  stories/tab/props-table.tsx
  stories/tab/tab.mdx
  stories/tab/tab.stories.tsx
Labels: enhancement

#690 [COMMPORTAL-195][SW] update PA font specs
  src/theme/font-spec/specs/pa-font-spec-set.ts
Labels: enhancement

#686 Enhance documentation for component tokens
  src/theme/colour-semantic/theme-helper.ts
  stories/button/button.mdx
  stories/button/button.stories.tsx
  stories/button/tokens-table.tsx
  stories/storybook-common/api-table/api-table-components.tsx
  stories/storybook-common/doc-table.tsx
  stories/storybook-common/index.ts
  stories/storybook-common/token-inspector.tsx
  stories/storybook-common/token-table/index.ts
  stories/storybook-common/token-table/token-table-components.tsx
  stories/storybook-common/token-table/token-table.tsx
  stories/storybook-common/token-table/types.ts
  stories/theme/component/a-component-token-introduction.mdx
  stories/theme/doc-elements/doc-semantic-colour-display.tsx
Labels: documentation
