Repository LifeSG/react-design-system, pull requests merged in 2025-06, with the labels that each got.

#695 Improve `OtpInput` accessibility
  src/otp-input/otp-input.tsx
  src/util/string-helper.ts
  tests/otp-input.spec.tsx/otp-input.spec.tsx
  tests/utils/string-helper.spec.ts
Labels: enhancement, a11y

#697 [MISC][JH] Fix missing background-color for timeline indicator (current variant)
  src/timeline/timeline.style.tsx
Labels: bug

#693 [CCUBE-1784][XY] Add A11y Playground Theme (Colours + Font Tokens)
  .storybook/preview-head.html
  .storybook/preview.ts
  src/theme/colour-primitive/specs/a11yplayground-colour-set.ts
  src/theme/colour-primitive/theme-helper.ts
  src/theme/colour-semantic/theme-helper.ts
  src/theme/font-spec/specs/a11yplayground-font-spec-set.ts
  src/theme/font-spec/theme-helper.ts
  src/theme/font/specs/a11yplayground-font-set.ts
  src/theme/font/theme-helper.ts
  src/theme/index.ts
  src/theme/types.ts
  stories/getting-started/installation.mdx
  stories/theme/a-introduction.mdx
  stories/theme/b-theme-introduction.mdx
  stories/theme/colour/a-colour-introduction.mdx
  stories/theme/colour/i-colour-a11yplayground.mdx
  stories/theme/font/a-font-introduction.mdx
  stories/theme/font/e-font-a11yplayground.mdx
Labels: enhancement

#702 Expose rootnode
  src/date-input/date-input.tsx
  src/date-input/types.ts
  src/date-navigator/date-navigator.tsx
  src/date-navigator/types.ts
  src/date-range-input/date-range-input.tsx
  src/date-range-input/types.ts
  src/input-multi-select/input-multi-select.tsx
  src/input-multi-select/types.ts
  src/input-nested-multi-select/input-nested-multi-select.tsx
  src/input-nested-select/input-nested-select.tsx
  src/input-nested-select/types.ts
  src/input-select/input-select.tsx
  src/input-select/types.ts
  src/select-histogram/select-histogram.tsx
  src/select-histogram/types.ts
  src/shared/dropdown-wrapper/element-with-dropdown.tsx
  stories/date-navigator/props-table.tsx
  stories/form/form-date-input/props-table.tsx
  stories/form/form-date-range-input/props-table.tsx
  stories/form/form-multi-select/props-table.tsx
  stories/form/form-nested-multi-select/props-table.tsx
  stories/form/form-nested-select/props-table.tsx
  stories/form/form-select-histogram/props-table.tsx
  stories/form/form-select/props-table.tsx
Labels: enhancement

#703 Commportal 607
  src/index.ts
  src/singpass-button/index.ts
  src/singpass-button/singpass-assets.ts
  src/singpass-button/singpass-button.style.tsx
  src/singpass-button/singpass-button.tsx
  src/singpass-button/types.ts
  stories/button/button.mdx
  stories/singpass-button/doc-elements.tsx
  stories/singpass-button/props-table.tsx
  stories/singpass-button/singpass-button.mdx
  stories/singpass-button/singpass-button.stories.tsx
Labels: enhancement

#709 Dark mode fixes
  src/breadcrumb/breadcrumb.style.tsx
  src/markup/markup.style.tsx
  src/navbar/drawer.styles.tsx
  src/navbar/navbar.styles.tsx
  src/select-histogram/select-histogram.styles.tsx
  src/select-histogram/select-histogram.tsx
  src/shared/fade-wrapper/fade-wrapper.style.tsx
Labels: bug

#713 [CCUBE-1820][XY] Add Button component tokens for A11y Playground
  src/theme/components/specs/a11yplayground-component-token-set.ts
  src/theme/components/theme-helper.ts
  src/theme/index.ts
  src/theme/types.ts
  stories/button/button.mdx
  stories/button/tokens-table.tsx
  stories/singpass-button/singpass-button.mdx
  stories/singpass-button/singpass-button.stories.tsx
  stories/singpass-button/tokens-table.tsx
  stories/theme/component/a-component-token-introduction.mdx
Labels: enhancement

#717 [MOL-18833][AT] increase gap for footer resource
  src/footer/footer-resource-addon.styles.tsx
Labels: enhancement

#708 [BOOKINGSG-7539][LS] Accessibility annotations for date input and date range input
  src/date-input/date-input.tsx
  src/date-range-input/date-range-input.tsx
  src/form/form-date-input.tsx
  src/form/form-date-range-input.tsx
  src/form/form-wrapper.tsx
  src/shared/internal-calendar/day-cell/day-cell.tsx
  src/shared/internal-calendar/day-cell/types.tsx
  src/shared/internal-calendar/fixed-range/fixed-range-calendar-day-view.tsx
  src/shared/internal-calendar/fixed-range/fixed-range-cell.tsx
  src/shared/internal-calendar/internal-calendar.tsx
  src/shared/internal-calendar/single/single-calendar-day-view.tsx
  src/shared/internal-calendar/single/single-cell.tsx
  src/shared/internal-calendar/standard/standard-calendar-day-view.tsx
  src/shared/internal-calendar/standard/standard-cell.tsx
  src/shared/internal-calendar/types.ts
  src/shared/internal-calendar/week/week-calendar-day-view.tsx
  src/shared/internal-calendar/week/week-day-cell.tsx
  src/shared/standalone-date-input/standalone-date-input.tsx
  tests/date-input/date-input.spec.tsx
Labels: enhancement, a11y
